<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MgSchema</name>
   <tag></tag>
   <elementGuidId>50c41706-4ab2-4cd1-aa9e-0cbf2d6b6d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/ul/li[2]/ul/a[2]/button/span/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eaf076cf-4417-41bb-a2e8-6aa51ef97d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItemText-root</value>
      <webElementGuid>ae160a02-0f80-4c1c-9cce-465b4b3fca3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MgSchema</value>
      <webElementGuid>0e5a65a7-a2b9-43af-a7b4-86789dc029e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jsx-1592603241&quot;]/div[2]/div[2]/div[@class=&quot;jss537&quot;]/div[@class=&quot;jss538&quot;]/ul[@class=&quot;MuiList-root jss545 MuiList-padding MuiList-subheader&quot;]/li[2]/ul[@class=&quot;jss547&quot;]/a[2]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiListItem-root jss550 MuiListItem-gutters&quot;]/span[@class=&quot;MuiButton-label&quot;]/div[@class=&quot;MuiListItemText-root&quot;]</value>
      <webElementGuid>85911b42-42b7-4df1-8933-66b6b659607e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/ul/li[2]/ul/a[2]/button/span/div[2]</value>
      <webElementGuid>c3001081-f608-477e-84c6-8495238a3ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MgTable'])[1]/following::div[2]</value>
      <webElementGuid>43efaf3a-4507-469b-8011-c9040da14d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v2020.02.29'])[1]/following::div[4]</value>
      <webElementGuid>c8cb2dcd-0954-41f3-827c-3be9fc24b657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MgRole'])[1]/preceding::div[2]</value>
      <webElementGuid>e81e576e-64b9-40c1-9e7c-3ecd43895a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button/span/div[2]</value>
      <webElementGuid>8ca448c3-8601-47b8-96eb-99000c3e9289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MgSchema' or . = 'MgSchema')]</value>
      <webElementGuid>2a9a10fc-c745-436c-9f15-719e1d7ef81f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
