<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MgTable</name>
   <tag></tag>
   <elementGuidId>43fd94e5-e1ba-48ce-aeab-c104409e1458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiListItemText-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/ul/li[2]/ul/a/button/span/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7f9ad19-d74b-452f-9e1d-f39b193869bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItemText-root</value>
      <webElementGuid>7d33b503-2be5-4e8b-947e-6b82497414f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MgTable</value>
      <webElementGuid>3d7db695-275b-4f29-ab35-df16c17b3eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jsx-1592603241&quot;]/div[2]/div[2]/div[@class=&quot;jss537&quot;]/div[@class=&quot;jss538&quot;]/ul[@class=&quot;MuiList-root jss545 MuiList-padding MuiList-subheader&quot;]/li[2]/ul[@class=&quot;jss547&quot;]/a[1]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiListItem-root jss550 MuiListItem-gutters&quot;]/span[@class=&quot;MuiButton-label&quot;]/div[@class=&quot;MuiListItemText-root&quot;]</value>
      <webElementGuid>a427ccb0-87bc-4df3-a369-1e1e7bbeda44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/ul/li[2]/ul/a/button/span/div[2]</value>
      <webElementGuid>e29ea854-d457-4d22-9e01-16aca30f1620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v2020.02.29'])[1]/following::div[2]</value>
      <webElementGuid>513e1871-f65c-4801-912f-6778815408bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MgSchema'])[1]/preceding::div[2]</value>
      <webElementGuid>0ab65a65-dc4a-4298-afa4-f338271b06db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[2]</value>
      <webElementGuid>7890c980-7db5-4079-a443-04af05088a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MgTable' or . = 'MgTable')]</value>
      <webElementGuid>5c92fe52-f6e3-406f-8623-c75afba3d4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
