<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rerun</name>
   <tag></tag>
   <elementGuidId>412f4d73-49ef-4ddc-bf74-442a5312efb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8fa5bf90-3188-4b6e-97b4-c6faac341ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-label</value>
      <webElementGuid>68ef6df5-acc8-46be-8ef2-17ef6591572d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rerun</value>
      <webElementGuid>cd88f456-02ee-4aea-86cb-6a60b742e4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jsx-1592603241&quot;]/div[2]/div[2]/div[@class=&quot;jss535&quot;]/div[@class=&quot;jss536&quot;]/div[@class=&quot;jss863&quot;]/div[@class=&quot;MuiSnackbar-root MuiSnackbar-anchorOriginBottomRight&quot;]/div[@class=&quot;MuiPaper-root MuiSnackbarContent-root MuiPaper-elevation6&quot;]/div[@class=&quot;MuiSnackbarContent-action&quot;]/div[1]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-containedSizeSmall MuiButton-sizeSmall&quot;]/span[@class=&quot;MuiButton-label&quot;]</value>
      <webElementGuid>cf144ad9-e5b8-4c40-958c-9af548f949a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/button[2]/span</value>
      <webElementGuid>b7762fc4-8a8f-4f78-b10c-da9e78fb2fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::span[2]</value>
      <webElementGuid>05caa994-d994-402d-8e21-3a6192129148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save your changes!'])[1]/following::span[3]</value>
      <webElementGuid>e76acd43-e344-46e6-9866-190e8f00689c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile &amp; Billing'])[1]/preceding::span[5]</value>
      <webElementGuid>64b8d23b-22ed-4f0d-860d-d65e1ff6a435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[6]</value>
      <webElementGuid>46b7fb33-198e-4e6c-85b8-14a319fb9688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rerun']/parent::*</value>
      <webElementGuid>1d981ae3-a96c-4424-9674-fadf5e7db7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]/span</value>
      <webElementGuid>a3fe6f67-c372-456f-b0d9-338808b36e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rerun' or . = 'Rerun')]</value>
      <webElementGuid>b7790a29-78b1-4407-b3bf-410e20cb1b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
