<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_newtables</name>
   <tag></tag>
   <elementGuidId>0234a8b1-ca01-4023-a434-b40d63ac33cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simple-tab-5 > span.MuiTab-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='simple-tab-5']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6029a0fd-47db-4391-bafb-bbecd06a924c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>a405b33c-d23c-45e8-a0ca-3e374b633274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>newtables</value>
      <webElementGuid>c92072e4-6ab9-402d-b771-fbab01cd0a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-tab-5&quot;)/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>764f8e87-f664-462c-a1a7-ef7a0c897ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='simple-tab-5']/span</value>
      <webElementGuid>5a989ed6-d880-44e8-bfef-669f16a9c798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='images'])[1]/following::span[2]</value>
      <webElementGuid>4044f72e-2344-4cb5-9f59-9960dac01fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='comments'])[1]/following::span[4]</value>
      <webElementGuid>15a6c741-3d30-41e4-bc7b-b22e75e5361d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/preceding::span[14]</value>
      <webElementGuid>028f198b-2901-471a-8210-2424a9a1b07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='newtables']/parent::*</value>
      <webElementGuid>cc6b1f25-2c72-4bc9-8248-1fc5ef8bab5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]/span</value>
      <webElementGuid>e0f38705-8a4d-46f2-b8f0-bb6906339a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'newtables' or . = 'newtables')]</value>
      <webElementGuid>2ca6fa24-d30a-4d36-aa45-3f009e8f2dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
