<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MgSchema</name>
   <tag></tag>
   <elementGuidId>69b8c06a-eabf-4c74-be84-764ccf00c0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/ul/li[2]/ul/a[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d05d3801-f2ea-4754-8da6-eeb010de9afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-label</value>
      <webElementGuid>5d72057f-f0ec-45a3-a2e6-4e64ff90d049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MgSchema</value>
      <webElementGuid>37854316-c5f6-4daf-907f-31fd1fd4d975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jsx-1592603241&quot;]/div[2]/div[2]/div[@class=&quot;jss537&quot;]/div[@class=&quot;jss538&quot;]/ul[@class=&quot;MuiList-root jss545 MuiList-padding MuiList-subheader&quot;]/li[2]/ul[@class=&quot;jss547&quot;]/a[2]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiListItem-root jss550 MuiListItem-gutters&quot;]/span[@class=&quot;MuiButton-label&quot;]</value>
      <webElementGuid>24bd05e2-92dd-494f-992b-cffee1f1e121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/ul/li[2]/ul/a[2]/button/span</value>
      <webElementGuid>9beed097-0ebe-4ebc-afb2-f2daf3d134b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MgTable'])[1]/following::span[2]</value>
      <webElementGuid>a4642a7b-9904-40ec-8618-1087a23fe3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v2020.02.29'])[1]/following::span[6]</value>
      <webElementGuid>59da48a1-5e00-4af4-9ab7-296f651498a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MgRole'])[1]/preceding::span[5]</value>
      <webElementGuid>44f9c530-d639-42a1-a40b-c7e0678a89ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button/span</value>
      <webElementGuid>488021a0-e66f-4db8-ba4c-a92607152b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MgSchema' or . = 'MgSchema')]</value>
      <webElementGuid>ecc50834-f5a3-4cef-9590-1a5594ce3c7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
