<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Type Newtable_MuiSvgIcon-root</name>
   <tag></tag>
   <elementGuidId>63e21d85-8133-4955-a8a5-482e3f7de601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Type Newtable'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4202132f-d7a4-4fd0-924b-b5c4cf5d2c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSvgIcon-root</value>
      <webElementGuid>374c9557-f41b-4f35-9e8a-11ba56100c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9378737-0721-40c1-931e-03b5c0e3a4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>b141c2ac-f524-4e52-bb13-f5f156903825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60cd420a-5289-4b31-94af-7350fceac17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>24ce97e8-7c1e-44c2-a648-7b5d5761c14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-1&quot;)/div[@class=&quot;jss1595&quot;]/table[@class=&quot;jss1596&quot;]/thead[1]/tr[@class=&quot;jss1597&quot;]/td[@class=&quot;jss1598&quot;]/div[1]/svg[@class=&quot;MuiSvgIcon-root&quot;]</value>
      <webElementGuid>03b0d89a-09ee-4861-938f-b86a5abd561f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type Newtable'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>f6565eb6-4e95-451a-8c26-dd84fadaf10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[7]/following::*[name()='svg'][1]</value>
      <webElementGuid>1f3ba187-ad24-41cd-a4e5-624cacb6be8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='name'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b941dc34-2883-40ac-b207-2c4d82edae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='String'])[4]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>0ac2de22-703d-43b0-983d-6c158f5c2580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
